# Generated by Django 3.2.24 on 2024-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emotional',
            field=models.BooleanField(default=False),
        ),
    ]
