# Generated by Django 3.2.24 on 2024-02-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyq', '0003_alter_img_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='sorted_objs',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
